name: app
description: "Alert System application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.3.0+1
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  localization: ^2.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  permission_handler: ^10.4.5
  animated_bottom_navigation_bar: ^1.3.3
  geolocator: ^11.0.0
  weather: ^3.1.1
  shimmer: ^3.0.0
  yandex_mapkit: ^3.4.0
  icons_launcher: ^2.1.7
  flutter_advanced_switch: ^3.0.1
  firebase_messaging: ^14.7.16
  firebase_core: ^2.25.4
  dio: ^5.4.1
  firebase_auth: ^4.17.4
  flutter_advanced_segment: ^3.0.2
  flutter_chat_bubble: ^2.0.2
  socket_io_client: ^2.0.3+1
  flutter_local_notifications: ^17.0.0

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      image_path: 'assets/icon_border.png'
      adaptive_background_image: 'assets/icon_background.png'
      adaptive_foreground_image: 'assets/icon_foregraunt.png'
      adaptive_round_image: 'assets/icon_round.png'
      enable: true
    ios:
      enable: true

dev_dependencies:
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  main_locale: ru
  enabled: true